# Process flow data
load and plot flow data, check the accuracy

## Set up, load data

In [6]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import numpy.matlib

Process Petar's Matlab data

In [ ]:
import os
from scipy.io import loadmat
from scipy import stats

num_domain = 6
sample_size = 500
num_class = 2
mat_path = '../data/DatasetFlow5/unnorm_balanced'
npz_path = '../data/DatasetFlow5/unnorm_balanced'
label_d = np.repeat(np.arange(num_domain), sample_size).T.reshape(sample_size * num_domain, 1)
label_y = np.matlib.repmat(np.repeat(np.arange(num_class), sample_size / num_class), 1, num_domain).T
y = np.concatenate((label_y, label_d), 1)

for i in range(28):
    train_mat_path = os.path.join(mat_path, 'flowtrain_%d_500_neqy_unnorm.mat'%(i+1))
    test_mat_path = os.path.join(mat_path, 'flowtest_%d_500_neqy_unnorm.mat'%(i+1))
    train_mat = loadmat(train_mat_path)
    test_mat = loadmat(test_mat_path)
    x = train_mat['DATA'][0][0].T
    for j in range(num_domain-2):
        x_train = train_mat['DATA'][0][j+1].T
        x = np.concatenate((x, x_train), 0)
    x_test = test_mat['DATA'][0][0].T
    x = np.concatenate((x, x_test), 0)
    x = stats.zscore(x)
    full_path = os.path.join(npz_path, 'flow_%d_500_neqy_unnorm.npz'%(i))
    np.savez(full_path, x=x, y=y)


Add Markov Blanket information to DAG matrix and save to .npz format

In [7]:
mat = np.load('../data/DatasetFlow5/dag_mat.npy')
print(mat)
MB = [0, 2, 3, 4]
full_path = '../data/DatasetFlow5/dag_mat.npz'
np.savez(full_path, mat=mat, MB=MB)

[[ 0.  0.  1.  1.  0.  1.]
 [ 1.  0.  1.  1.  1.  1.]
 [ 0.  0.  0. -1.  1.  1.]
 [ 0.  0. -1.  0.  1.  1.]]


Create DatasetFlow3: 3 source domains .npz

In [17]:
import os
from scipy.io import loadmat
from scipy import stats

num_domain = 4
sample_size = 500
num_class = 2
mat_path = '../data/DatasetFlow5/unnorm_balanced'
npz_path = '../data/DatasetFlow3/unnorm_balanced'
label_d = np.repeat(np.arange(num_domain), sample_size).T.reshape(sample_size * num_domain, 1)
label_y = np.matlib.repmat(np.repeat(np.arange(num_class), sample_size / num_class), 1, num_domain).T
y = np.concatenate((label_y, label_d), 1)

for i in range(28):
    train_mat_path = os.path.join(mat_path, 'flowtrain_%d_500_neqy_unnorm.mat'%(i+1))
    test_mat_path = os.path.join(mat_path, 'flowtest_%d_500_neqy_unnorm.mat'%(i+1))
    train_mat = loadmat(train_mat_path)
    test_mat = loadmat(test_mat_path)
    x = train_mat['DATA'][0][0].T
    for j in range(num_domain-2):
        x_train = train_mat['DATA'][0][j+1].T
        x = np.concatenate((x, x_train), 0)
    x_test = test_mat['DATA'][0][0].T
    x = np.concatenate((x, x_test), 0)
    x = stats.zscore(x)
    full_path = os.path.join(npz_path, 'flow_%d_500_neqy_unnorm.npz'%(i))
    np.savez(full_path, x=x, y=y)
